// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg9XtgAX_M793oUWDp3ATQBFUCPSFNfEE',
    appId: '1:167525615232:web:734fbc9d4d4378691b8865',
    messagingSenderId: '167525615232',
    projectId: 'bloodbank-30bad',
    authDomain: 'bloodbank-30bad.firebaseapp.com',
    storageBucket: 'bloodbank-30bad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80Za_-42bnaI03uaYrHDD7BfHdm5NuWY',
    appId: '1:167525615232:android:fba89abb6e8d96711b8865',
    messagingSenderId: '167525615232',
    projectId: 'bloodbank-30bad',
    storageBucket: 'bloodbank-30bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHGt0AoVWfzauSavitnpPvM902DPmVYA4',
    appId: '1:167525615232:ios:170a1b887ca3d4a01b8865',
    messagingSenderId: '167525615232',
    projectId: 'bloodbank-30bad',
    storageBucket: 'bloodbank-30bad.firebasestorage.app',
    iosBundleId: 'com.example.bloodpoint',
  );
}
